sudo: true
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
before_script:
  - git clone https://github.com/sitegeist/git-hooks.git $HOME/.sitegeist-hooks
  - cd $HOME/.sitegeist-hooks
  - ./install
  - cd $TRAVIS_BUILD_DIR
script:
  - bats ./tests/cli
